variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_PROJECT_PATH

stages:
  - deploy

cache:
  paths:
    - node_modules/

deploy-prod:
  stage: deploy
  script:
    - yarn
    - CI=false yarn build
    - sudo rm -rf /var/www/safemoon/pro
    - sudo mv ./build /var/www/safemoon/pro
    - sudo mv ./safemoon.json /var/www/safemoon/pro
    - sudo cp -r /var/www/safemoon/images/* /var/www/safemoon/pro/images/
  only:
    - master
  tags:
    - shared

deploy-dev:
  stage: deploy
  script:
    - yarn
    - CI=false yarn build
    - sudo rm -rf /var/www/safemoon/dev
    - sudo mv ./build /var/www/safemoon/dev
    - sudo mv ./safemoon.json /var/www/safemoon/pro
  only:
    - develop
  tags:
    - shared
